/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2pnetwork;

import Util.Constants;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Moreno
 */
public class Application extends javax.swing.JFrame {

    private DefaultListModel model;
    private int lastSelectedIndex;
    private final List<Peer> peerList;

    /**
     * Creates new form Application
     */
    public Application() {

        peerList = new ArrayList<>();

        initComponents();

        StartBootPeer();
    }

    private void StartBootPeer() {

        byte id = 0;
        Peer peer = new Peer(id, Constants.SERVERPORT);

        peer.setBootPeer(true);
        peer.Start();

        Thread peerThread = new Thread(peer);
        peerThread.start();

        peerList.add(peer);

        model = new DefaultListModel();

        list_peerList.setModel(model);

        UpdatePeerListData();
    }

    private void UpdatePeerListData() {
        model.clear();

        for (int i = 0; i < peerList.size(); i++) {
            Peer peer = peerList.get(i);
            String displayName = "Peer " + peer.getId() + " references= " + peer.peerReferences.toString();

            model.add(i, displayName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_peerList = new javax.swing.JList<>();
        buton_AddPeer = new javax.swing.JButton();
        field_Port = new javax.swing.JTextField();
        label_Port = new javax.swing.JLabel();
        label_Address = new javax.swing.JLabel();
        label_ID = new javax.swing.JLabel();
        button_Refresh = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_peerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_peerList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_peerListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_peerList);

        buton_AddPeer.setText("Add Peer");
        buton_AddPeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_AddPeerActionPerformed(evt);
            }
        });

        field_Port.setText("1201");

        label_Port.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Port.setText("Port");

        label_Address.setText("jLabel1");

        label_ID.setText("jLabel2");

        button_Refresh.setText("Refresh List");
        button_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buton_AddPeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_Port, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(field_Port))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(label_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buton_AddPeer)
                        .addComponent(button_Refresh))
                    .addComponent(label_ID))
                .addGap(1, 1, 1)
                .addComponent(label_Port)
                .addGap(3, 3, 3)
                .addComponent(field_Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_AddPeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_AddPeerActionPerformed
        // TODO add your handling code here:

        byte id = Constants.DISCONNECTED_PEERID;

        Peer newPeer = new Peer(id, Integer.parseInt(field_Port.getText()));

        newPeer.Start();

        newPeer.JoinNetworkWithIP("localhost", Constants.SERVERPORT);

        Thread peerThread = new Thread(newPeer);
        peerThread.start();

        peerList.add(newPeer);

        int portNumber = Integer.parseInt(field_Port.getText());
        portNumber++;
        field_Port.setText(Integer.toString(portNumber));

        UpdatePeerListData();
    }//GEN-LAST:event_buton_AddPeerActionPerformed

    private void list_peerListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_peerListValueChanged
        // TODO add your handling code here:

        if (evt.getValueIsAdjusting()) {
            return;
        }

        int index = evt.getLastIndex() == lastSelectedIndex ? evt.getFirstIndex() : evt.getLastIndex();

        lastSelectedIndex = index;
        Peer selectedPeer = peerList.get(lastSelectedIndex);

        label_Address.setText(selectedPeer.getAddress());
        label_ID.setText(Integer.toString(selectedPeer.getId()));

        System.out.println("Selected" + selectedPeer.toString());
    }//GEN-LAST:event_list_peerListValueChanged

    private void button_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RefreshActionPerformed

        UpdatePeerListData();
    }//GEN-LAST:event_button_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_AddPeer;
    private javax.swing.JToggleButton button_Refresh;
    private javax.swing.JTextField field_Port;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Address;
    private javax.swing.JLabel label_ID;
    private javax.swing.JLabel label_Port;
    private javax.swing.JList<String> list_peerList;
    // End of variables declaration//GEN-END:variables
}
